# Generated by Django 6.0.5 on 2026-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_anonymous_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
